Pipeline improvement, changed behavior when deployment couldn't be found

diff --git a/.github/workflows/deploy-otp.yml b/.github/workflows/deploy-otp.yml
--- a/.github/workflows/deploy-otp.yml
+++ b/.github/workflows/deploy-otp.yml
@@ -40,7 +40,8 @@ jobs:
       - name: Show deployment logs on failure (dev)
         if: failure()
         run: |
-          az deployment group show --resource-group rg-environment-dev --name deploy-otp-dev
+          az deployment group show --resource-group rg-environment-dev --name deploy-otp-dev || echo "No deployment found (likely validation failure)"
+          
 
   deploy-test:
     runs-on: ubuntu-latest
@@ -77,7 +78,7 @@ jobs:
       - name: Show deployment logs on failure (test)
         if: failure()
         run: |
-          az deployment group show --resource-group rg-environment-test --name deploy-otp-test
+          az deployment group show --resource-group rg-environment-test --name deploy-otp-test || echo "No deployment found (likely validation failure)"
 
   deploy-prod:
     runs-on: ubuntu-latest
@@ -114,4 +115,4 @@ jobs:
       - name: Show deployment logs on failure (prod)
         if: failure()
         run: |
-          az deployment group show --resource-group rg-environment-prod --name deploy-otp-prod
+          az deployment group show --resource-group rg-environment-prod --name deploy-otp-prod || echo "No deployment found (likely validation failure)"
